spring:
  profiles:
    active: dev

---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.huang.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的相关配置
spring:
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver      #mysql驱动
    url: jdbc:mysql://192.168.1.199:3306/springcloud01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5           #数据库连接池的最小维持连接数
      initial-size: 5       #初始化连接数
      max-total: 5          #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间

#Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka上的默认描述信息!

#info配置
info:
  app.name: huang-springcloud
  company.name: www.huang.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.huang.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的相关配置
spring:
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver      #mysql驱动
    url: jdbc:mysql://192.168.1.199:3306/springcloud02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5           #数据库连接池的最小维持连接数
      initial-size: 5       #初始化连接数
      max-total: 5          #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间

#Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka上的默认描述信息!

#info配置
info:
  app.name: huang-springcloud
  company.name: www.huang.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}